# Generated by Django 5.2.9 on 2026-02-05 07:25

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DroneEarlyInform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(max_length=50)),
                ('main_step', models.CharField(max_length=50)),
                ('custom_end_step', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drone_early_inform',
                'constraints': [models.UniqueConstraint(fields=('line_id', 'main_step'), name='uniq_dro_erl_inf_ln_id_mn_stp')],
            },
        ),
        migrations.CreateModel(
            name='DroneSOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sop_key', models.CharField(max_length=300, unique=True)),
                ('line_id', models.CharField(blank=True, max_length=50, null=True)),
                ('sdwt_prod', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_type', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_group', models.CharField(blank=True, max_length=50, null=True)),
                ('eqp_id', models.CharField(blank=True, max_length=50, null=True)),
                ('chamber_ids', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_id', models.CharField(blank=True, max_length=50, null=True)),
                ('proc_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ppid', models.CharField(blank=True, max_length=50, null=True)),
                ('main_step', models.CharField(blank=True, max_length=50, null=True)),
                ('metro_current_step', models.CharField(blank=True, max_length=50, null=True)),
                ('metro_steps', models.CharField(blank=True, max_length=1000, null=True)),
                ('metro_end_step', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('knox_id', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user_sdwt_prod', models.CharField(blank=True, max_length=50, null=True)),
                ('defect_url', models.TextField(blank=True, null=True)),
                ('send_jira', models.SmallIntegerField(blank=True, db_default=0, default=0, null=True)),
                ('instant_inform', models.SmallIntegerField(default=0)),
                ('needtosend', models.SmallIntegerField(default=1)),
                ('custom_end_step', models.CharField(blank=True, max_length=50, null=True)),
                ('inform_step', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_key', models.CharField(blank=True, max_length=50, null=True)),
                ('informed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'drone_sop',
                'indexes': [models.Index(fields=['send_jira', 'needtosend'], name='idx_dro_sop_snd_jir_nts'), models.Index(fields=['sdwt_prod'], name='idx_dro_sop_sdw_prd'), models.Index(fields=['created_at', 'id'], name='idx_dro_sop_crt_at_id'), models.Index(fields=['user_sdwt_prod', 'created_at', 'id'], name='idx_dro_sop_usr_sdw_prd_dd5e5'), models.Index(fields=['send_jira'], name='idx_dro_sop_snd_jir'), models.Index(fields=['knox_id'], name='idx_dro_sop_knx_id'), models.Index(condition=models.Q(('needtosend', 1), ('send_jira', 0), ('status', 'COMPLETE')), fields=['id'], name='idx_dro_sop_id_jir_pen')],
                'constraints': [models.UniqueConstraint(fields=('line_id', 'eqp_id', 'chamber_ids', 'lot_id', 'main_step'), name='uniq_dro_sop_ln_id_eqp_i_92d25')],
            },
        ),
        migrations.CreateModel(
            name='DroneSopJiraUserTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sdwt_prod', models.CharField(max_length=50, unique=True)),
                ('template_key', models.CharField(blank=True, max_length=50, null=True)),
                ('jira_key', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now())),
                ('updated_at', models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now())),
            ],
            options={
                'db_table': 'drone_sop_jira_user_template',
                'indexes': [models.Index(fields=['user_sdwt_prod'], name='idx_dro_sop_jir_usr_tmpl_a256d')],
            },
        ),
    ]
